version: '3.8'

services:
  mongo_testing_database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}


    ports:
      - 127.0.0.1:${MONGO_PORT}:27017
    volumes:
      - ./mongo_init.sh:/docker-entrypoint-initdb.d/mongo_init.sh:ro
 
