version: '3.8'

services:
  mongo_testing_database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}


    ports:
      - 127.0.0.1:${MONGO_PORT}:27017
    volumes:
      - ./mongo_init.sh:/docker-entrypoint-initdb.d/mongo_init.sh:ro

  car_api:
    image: car_platform_api:v0.9
    environment:
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_HOST: ${DOCKER_MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      NODE_ENV: 'DEV'
    depends_on:
      - mongo_testing_database

    healthcheck:
      test: curl --fail -s http://localhost:4000/api/healthcheck || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s


    ports:
      - 3000:4000

  
 
