version: '3.1'

services:
  mongo_testing_database:
    image: mongo:focal
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_DB: ${MONGO_DB}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 127.0.0.1:${MONGO_PORT}:27017
    volumes:
      - ./docker/mongo:/var/lib/mongo/data
