name: Run continuous integration test

on:
  push:

jobs:
  unit_lint_load_test:
    runs-on: ubuntu-latest
    services:
      mongo:
          image: mongo:focal
          env:
              MONGO_USER: ${{ secrets.MONGO_USER }}
              MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
              MONGO_DB: ${{ secrets.MONGO_DB }}
              MONGO_PORT: 27017
          ports:
              - 27017:27017
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:

    - name: Display workflow infos
      run: |
        echo The job_id is: $GITHUB_JOB
        echo "The id of this action is: $GITHUB_ACTION"
        echo "The run id is: $GITHUB_RUN_ID"
        echo "The GitHub Actor's username is: $GITHUB_ACTOR"
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Create env file'
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
          node-version: '16'

    - name: Initialise the project
      run: npm install

    - name: Check project syntax with ESLINT
      run: npm run lint

    - name: Run unit test with MochaJS
      run: npm run test